name: "KiBot"

on:
  pull_request:
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

jobs:
  Preflight:
    env:
      BaseFileName: TBM930_De-ice_panel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v1
        with:
          config: .kibot/preflight.kibot.yaml
          schema: "*.sch"
          board: ${{ env.BaseFileName }}.kicad_pcb
