# This workflow runs erc and drc checks on every pull request that touches a scehmatic or PCB file.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.
name: "KiBot"

on:
  pull_request:
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

jobs:
  Preflight:
    env:
      # Set this to the base filename of your project.
      BaseFileName: TBM930_De-ice_panel
      Timezone: America/Los_Angeles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # Do a string replacement in the PCB file to set the version and date.
      # Any instance of %%version%% in the schematic gets replaced with the release version.
      # Any instance of %%date%% in the schematic gets replaced with the release date and time.
      - name: Set PCB and date
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: ".*.sch"
          find: "%%date%%"
          date: ${{ steps.date.outputs.date }}

      - uses: INTI-CMNB/KiBot@v1
        with:
          config: .kibot/preflight.kibot.yaml
          schema: ${{ env.BaseFileName }}.sch
          board: ${{ env.BaseFileName }}.kicad_pcb

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: KiBotOutput/**
