name: "KiBot"

on:
  pull_request:
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

jobs:
  Preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: INTI-CMNB/KiBot@v1
        with:
          config: ".kibot/preflight.kibot.yaml"
          schema: "TBM930_De-ice_panel.sch"
          board: "TBM930_De-ice_panel.kicad_pcb"
