name: "KiBot"

on:
  pull_request:
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

jobs:
  Preflight:
    env:
      BaseFileName: TBM930_De-ice_panel
      Timezone: "America/Los Angeles"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=${{ env.Timezone }} date +'%Y-%m-%d %T')"
      - name: Print current date
        id: print_date
        run: echo ${{ steps.date.outputs.date }}
      - uses: INTI-CMNB/KiBot@v1
        with:
          config: .kibot/preflight.kibot.yaml
          schema: ${{ env.BaseFileName }}.sch
          board: ${{ env.BaseFileName }}.kicad_pcb
